CREATE DATABASE IF NOT EXISTS `mini_bon_coin` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `mini_bon_coin`;

DROP TABLE IF EXISTS UTILISATEUR;
CREATE TABLE IF NOT EXISTS UTILISATEUR(
   Id_Utilisateur INT AUTO_INCREMENT,
   pseudo VARCHAR(50) NOT NULL,
   password VARCHAR(50) NOT NULL,
   email VARCHAR(50) NOT NULL,
   date_inscrit DATETIME NOT NULL,
   PRIMARY KEY(Id_Utilisateur),
   UNIQUE(email)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE IF NOT EXISTS CATEGORY(
   Id_category INT AUTO_INCREMENT,
   nom_category VARCHAR(50) NOT NULL,
   PRIMARY KEY(Id_category),
   UNIQUE(nom_category)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS ANNONCE;
CREATE TABLE IF NOT EXISTS ANNONCE(
   Id_ANNONCE INT AUTO_INCREMENT,
   titre VARCHAR(50) NOT NULL,
   description VARCHAR(50),
   prix DECIMAL(16, 2) NOT NULL,
   photo VARCHAR(100),
   date_public DATETIME NOT NULL,
   Id_category INT NOT NULL,
   Id_Utilisateur INT,
   PRIMARY KEY(Id_ANNONCE),
   UNIQUE(photo),
   FOREIGN KEY(Id_category) REFERENCES CATEGORY(Id_category),
   FOREIGN KEY(Id_Utilisateur) REFERENCES UTILISATEUR(Id_Utilisateur)
) ENGINE = InnoDB;